// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufntljxsbsygqvighyiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbnRsanhzYnN5Z3F2aWdoeWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDMxOTMsImV4cCI6MjA2Njg3OTE5M30.9eJ6x_bh9dvQqMRpAOgs7qKAsspEQS8yWd_se2ifXEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});